const translations={
 km:{brand:"ផ្លូវសុវត្ថិភាព",navSigns:"ផ្លាកសញ្ញា",navFines:"ការផាកពិន័យ",navGuide:"មគ្គុទ្ទេសក៍",eyebrow:"មគ្គុទ្ទេសក៍សុវត្ថិភាពផ្លូវគោកកម្ពុជា",heroTitle:'ស្គាល់ស្លាក។<br><span>បើកបរដោយសុវត្ថិភាព។</span>',heroText:"ស្វែងយល់ពីផ្លាកសញ្ញាចរាចរណ៍ និយមន័យ និងការផាកពិន័យក្នុងកន្លែងតែមួយ—រចនាឡើងឱ្យងាយអាន និងងាយស្វែងរក។",explore:"ចាប់ផ្តើមស្វែងយល់",random:"បង្ហាញផ្លាកចៃដន្យ",statSigns:"ផ្លាកសំខាន់ៗ",statCats:"ប្រភេទ",statLangs:"ភាសា",ticker1:"ពាក់មួកសុវត្ថិភាព",ticker2:"គោរពល្បឿនកំណត់",ticker3:"កុំប្រើទូរសព្ទពេលបើកបរ",ticker4:"ឈប់ពេលភ្លើងក្រហម",catalogKicker:"បណ្ណាល័យផ្លាកសញ្ញា",catalogTitle:"ស្វែងរកអ្វីដែលអ្នក<br>ចង់ស្គាល់។",catalogText:"ចុចលើផ្លាកណាមួយ ដើម្បីមើលនិយមន័យ សកម្មភាពត្រឹមត្រូវ និងព័ត៌មានផាកពិន័យ។",filterAll:"ទាំងអស់",filterWarning:"សញ្ញាប្រុងប្រយ័ត្ន",filterProhibition:"សញ្ញាហាមឃាត់",filterMandatory:"សញ្ញាបញ្ជា",filterInformation:"សញ្ញាព័ត៌មាន",tapHint:"ចុចលើផ្លាកដើម្បីមើលលម្អិត",noResults:"រកមិនឃើញផ្លាកសញ្ញា",tryAgain:"សូមសាកល្បងពាក្យផ្សេង ឬជ្រើសប្រភេទទាំងអស់។",fineKicker:"យល់ដឹងពីការផាកពិន័យ",fineTitle:"យានយន្តផ្សេងគ្នា។<br>កម្រិតពិន័យផ្សេងគ្នា។",fineText:"ការមិនគោរពផ្លាកហាមឃាត់ ផ្លាកបញ្ជា ផ្លាកសិទ្ធិអាទិភាព ឬគំនូសចរាចរណ៍ ត្រូវបានគិតតាមប្រភេទយានយន្ត។",moto:"ម៉ូតូ / ត្រីចក្រយាន",lightVehicle:"រថយន្តធុនស្រាល",heavyVehicle:"រថយន្តធុនធ្ងន់",typicalFine:"ការផាកពិន័យសម្រាប់ការមិនគោរពស្លាក",fineNote:"* ករណីលើសល្បឿន ការប្រណាំង ឬស្រវឹង មានតារាងពិន័យដាច់ដោយឡែក។",guideKicker:"ចំណាំឆាប់យល់",guideTitle:"រូបរាង និងពណ៌<br>ប្រាប់អ្នកមុនគេ។",guideText:"រៀនចំណាំតាមរូបរាង និងពណ៌ ដើម្បីស្គាល់មុខងារផ្លាកបានលឿន ទោះមើលពីចម្ងាយក៏ដោយ។",redTitle:"រង្វង់ក្រហម",redText:"ភាគច្រើនសម្គាល់ការហាមឃាត់ ឬកំណត់។",yellowTitle:"ត្រីកោណក្រហម",yellowText:"ព្រមានពីហានិភ័យ ឬស្ថានភាពផ្លូវខាងមុខ។",blueTitle:"រង្វង់ខៀវ",blueText:"បញ្ជាសកម្មភាពដែលអ្នកបើកបរត្រូវអនុវត្ត។",infoTitle:"ការ៉េខៀវ",infoText:"ផ្តល់ព័ត៌មានទីតាំង សេវា និងទិសដៅ។",sourceKicker:"ប្រភព និងសេចក្តីជូនដំណឹង",sourceTitle:"សម្រាប់ការសិក្សា និងការយល់ដឹងទូទៅ",sourceText:"ទិន្នន័យពិន័យយោងតាមអនុក្រឹត្យលេខ ៣៩ អនក្រ.បក ចុះថ្ងៃទី១៧ ខែមីនា ឆ្នាំ២០២០។ ចំនួនពិន័យអាចអាស្រ័យលើអំពើល្មើសជាក់ស្តែង ប្រភេទយានយន្ត និងការកែប្រែច្បាប់ថ្មី។",officialSource:"មើលប្រភពផ្លូវការ",footerText:"រៀន • គោរព • សុវត្ថិភាព",search:"ស្វែងរកផ្លាកសញ្ញា...",results:n=>`បង្ហាញ ${n} ផ្លាក`,category:{warning:"ប្រុងប្រយ័ត្ន",prohibition:"ហាមឃាត់",mandatory:"បញ្ជា",information:"ព័ត៌មាន"},meaning:"និយមន័យ",action:"អ្វីដែលត្រូវធ្វើ",penalty:"ការផាកពិន័យ",notFixed:"មិនមានពិន័យថេរដោយផ្ទាល់",depends:"អាស្រ័យលើអំពើល្មើសដែលកើតឡើង",legalNote:"ចំនួននេះជាការណែនាំយោងតាមអនុក្រឹត្យលេខ ៣៩។ សូមពិនិត្យប្រភពផ្លូវការសម្រាប់ករណីជាក់ស្តែង។"},
 en:{brand:"RoadSafe KH",navSigns:"Road signs",navFines:"Fines",navGuide:"Quick guide",eyebrow:"Cambodia road safety guide",heroTitle:'Know the sign.<br><span>Drive with confidence.</span>',heroText:"Explore essential road signs, their meanings and fine guidance in one clear, searchable bilingual guide.",explore:"Explore the signs",random:"Show a random sign",statSigns:"essential signs",statCats:"categories",statLangs:"languages",ticker1:"Always wear a helmet",ticker2:"Respect posted speed limits",ticker3:"Never use a phone while driving",ticker4:"Stop at red lights",catalogKicker:"Road sign library",catalogTitle:"Find what you<br>need to know.",catalogText:"Open any sign to see its meaning, the right action to take and relevant fine guidance.",filterAll:"All signs",filterWarning:"Warning",filterProhibition:"Prohibition",filterMandatory:"Mandatory",filterInformation:"Information",tapHint:"Select a sign for details",noResults:"No signs found",tryAgain:"Try another term or select all categories.",fineKicker:"Understand the penalties",fineTitle:"Different vehicles.<br>Different fine levels.",fineText:"Disobeying prohibition, mandatory or priority signs and road markings is fined according to vehicle type.",moto:"Motorcycle / Tuk-tuk",lightVehicle:"Light vehicle",heavyVehicle:"Heavy vehicle",typicalFine:"Fine for disobeying a regulatory sign",fineNote:"* Speeding, racing and drink-driving use separate penalty schedules.",guideKicker:"Recognise signs quickly",guideTitle:"Shape and colour<br>speak first.",guideText:"Learn the visual system to understand a sign's purpose quickly, even from a distance.",redTitle:"Red circle",redText:"Usually signals a prohibition or restriction.",yellowTitle:"Red triangle",yellowText:"Warns of a hazard or changing road condition ahead.",blueTitle:"Blue circle",blueText:"Shows an action that road users must follow.",infoTitle:"Blue square",infoText:"Provides directions, locations and service information.",sourceKicker:"Sources and notice",sourceTitle:"For learning and general awareness",sourceText:"Fine guidance references Sub-Decree No. 39 ANKr.BK dated 17 March 2020. The amount can vary by the actual offence, vehicle category and later legal changes.",officialSource:"View official source",footerText:"Learn • Respect • Arrive safely",search:"Search road signs...",results:n=>`${n} signs shown`,category:{warning:"Warning",prohibition:"Prohibition",mandatory:"Mandatory",information:"Information"},meaning:"Meaning",action:"What to do",penalty:"Fine guidance",notFixed:"No standalone fixed fine",depends:"Depends on the resulting offence",legalNote:"Amounts are a learning guide based on Sub-Decree No. 39. Check the official source for a specific case."}
};

const signImages={
 stop:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Cambodia_road_sign_R3-01.svg/250px-Cambodia_road_sign_R3-01.svg.png",
 "give-way":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Cambodia_road_sign_R3-02.svg/250px-Cambodia_road_sign_R3-02.svg.png",
 "no-entry":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Cambodia_road_sign_R1-04.svg/250px-Cambodia_road_sign_R1-04.svg.png",
 "no-left":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Cambodia_road_sign_R1-01.svg/250px-Cambodia_road_sign_R1-01.svg.png",
 "no-right":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Cambodia_road_sign_R1-02.svg/250px-Cambodia_road_sign_R1-02.svg.png",
 "no-uturn":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Cambodia_road_sign_R1-03.svg/250px-Cambodia_road_sign_R1-03.svg.png",
 "no-overtaking":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Cambodia_road_sign_R1-25.svg/250px-Cambodia_road_sign_R1-25.svg.png",
 "speed-50":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Cambodia_road_sign_R1-41%2850%29.svg/250px-Cambodia_road_sign_R1-41%2850%29.svg.png",
 "no-parking":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Cambodia_road_sign_R1-19.svg/250px-Cambodia_road_sign_R1-19.svg.png",
 "no-stopping":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Cambodia_road_sign_R1-20.svg/250px-Cambodia_road_sign_R1-20.svg.png",
 "weight-limit":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Cambodia_road_sign_R1-07.svg/250px-Cambodia_road_sign_R1-07.svg.png",
 "height-limit":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Cambodia_road_sign_R1-09.svg/250px-Cambodia_road_sign_R1-09.svg.png",
 straight:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Cambodia_road_sign_R2-10.svg/250px-Cambodia_road_sign_R2-10.svg.png",
 "turn-left":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Cambodia_road_sign_R2-08.svg/250px-Cambodia_road_sign_R2-08.svg.png",
 "turn-right":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Cambodia_road_sign_R2-07.svg/250px-Cambodia_road_sign_R2-07.svg.png",
 roundabout:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Cambodia_road_sign_R3-03.svg/250px-Cambodia_road_sign_R3-03.svg.png",
 "keep-right":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Cambodia_road_sign_R2-01.svg/250px-Cambodia_road_sign_R2-01.svg.png",
 "left-curve":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Cambodia_road_sign_W1-03.svg/250px-Cambodia_road_sign_W1-03.svg.png",
 crossroad:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Cambodia_road_sign_W1-15.svg/250px-Cambodia_road_sign_W1-15.svg.png",
 pedestrian:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Cambodia_road_sign_W1-34.svg/250px-Cambodia_road_sign_W1-34.svg.png",
 children:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Cambodia_road_sign_W1-33.svg/250px-Cambodia_road_sign_W1-33.svg.png",
 roadworks:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Cambodia_road_sign_W2-01.svg/250px-Cambodia_road_sign_W2-01.svg.png",
 slippery:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Cambodia_road_sign_W1-38.svg/250px-Cambodia_road_sign_W1-38.svg.png",
 "narrow-bridge":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Cambodian_Narrow_Bridge_Sign.svg/250px-Cambodian_Narrow_Bridge_Sign.svg.png",
 signals:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/Cambodia_road_sign_W1-42.svg/250px-Cambodia_road_sign_W1-42.svg.png",
 parking:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Cambodia_road_sign_G4-01.svg/250px-Cambodia_road_sign_G4-01.svg.png",
 hospital:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Cambodia_road_sign_G4-07.svg/250px-Cambodia_road_sign_G4-07.svg.png",
 fuel:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Cambodia_road_sign_G4-10.svg/250px-Cambodia_road_sign_G4-10.svg.png",
 "one-way":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Cambodia_road_sign_G4-39.svg/250px-Cambodia_road_sign_G4-39.svg.png"
};

const signs=[
 {id:"stop",cat:"prohibition",shape:"stop",symbol:"STOP",km:{name:"ឈប់",desc:"ត្រូវឈប់យានយន្តទាំងស្រុង មុនចូលផ្លូវប្រសព្វ ឬចំណុចដែលបានកំណត់។",action:"ឈប់មុនគំនូសឈប់ មើលឆ្វេង-ស្តាំ និងបន្តដំណើរពេលមានសុវត្ថិភាព។"},en:{name:"Stop",desc:"Come to a complete stop before entering the junction or marked point.",action:"Stop before the line, check both directions and proceed only when safe."}},
 {id:"give-way",cat:"prohibition",shape:"yield",symbol:"",km:{name:"ផ្តល់សិទ្ធិអាទិភាព",desc:"ត្រូវផ្តល់ផ្លូវដល់យានយន្តដែលកំពុងចរាចរលើផ្លូវមានអាទិភាព។",action:"បន្ថយល្បឿន ត្រៀមឈប់ និងចូលផ្លូវតែនៅពេលចន្លោះមានសុវត្ថិភាព។"},en:{name:"Give way",desc:"Yield to traffic travelling on the priority road.",action:"Slow down, prepare to stop and enter only when there is a safe gap."}},
 {id:"no-entry",cat:"prohibition",shape:"circle-red",symbol:"bar",km:{name:"ហាមចូល",desc:"យានយន្តមិនត្រូវចូលពីទិសនេះឡើយ។",action:"កុំបន្តទៅមុខ។ ស្វែងរកផ្លូវចូលឬទិសដៅផ្សេង។"},en:{name:"No entry",desc:"Vehicles must not enter from this direction.",action:"Do not continue. Find another permitted route."}},
 {id:"no-left",cat:"prohibition",shape:"circle-red",symbol:"leftSlash",km:{name:"ហាមបត់ឆ្វេង",desc:"មិនអនុញ្ញាតឱ្យបត់ឆ្វេងនៅចំណុចនេះ។",action:"បន្តត្រង់ ឬប្រើទិសដែលផ្លាកផ្សេងអនុញ្ញាត។"},en:{name:"No left turn",desc:"Turning left is prohibited at this point.",action:"Continue straight or follow another permitted direction."}},
 {id:"no-right",cat:"prohibition",shape:"circle-red",symbol:"rightSlash",km:{name:"ហាមបត់ស្តាំ",desc:"មិនអនុញ្ញាតឱ្យបត់ស្តាំនៅចំណុចនេះ។",action:"បន្តត្រង់ ឬប្រើទិសដែលផ្លាកផ្សេងអនុញ្ញាត។"},en:{name:"No right turn",desc:"Turning right is prohibited at this point.",action:"Continue straight or follow another permitted direction."}},
 {id:"no-uturn",cat:"prohibition",shape:"circle-red",symbol:"uSlash",km:{name:"ហាមបត់ត្រឡប់ក្រោយ",desc:"មិនអនុញ្ញាតឱ្យបត់ត្រឡប់ទិសនៅតំបន់នេះ។",action:"បន្តដំណើរទៅកាន់ចំណុចដែលអនុញ្ញាតឱ្យបត់ត្រឡប់។"},en:{name:"No U-turn",desc:"Making a U-turn is prohibited here.",action:"Continue until you reach a location where a U-turn is permitted."}},
 {id:"no-overtaking",cat:"prohibition",shape:"circle-red",symbol:"cars",km:{name:"ហាមវ៉ាជែង",desc:"ហាមយានយន្តវ៉ាជែងយានយន្តផ្សេងនៅលើកំណាត់ផ្លូវនេះ។",action:"រក្សាគន្លង ល្បឿន និងគម្លាតសុវត្ថិភាព។"},en:{name:"No overtaking",desc:"Overtaking other vehicles is prohibited on this section.",action:"Stay in lane and maintain a safe speed and following distance."}},
 {id:"speed-50",cat:"prohibition",shape:"circle-red",symbol:"50",fine:"speed",km:{name:"ល្បឿនកំណត់ ៥០",desc:"ល្បឿនអតិបរមាអនុញ្ញាតគឺ ៥០ គីឡូម៉ែត្រក្នុងមួយម៉ោង។",action:"បន្ថយល្បឿនឱ្យមិនលើស ៥០ km/h មុនដល់ផ្លាក។"},en:{name:"50 km/h speed limit",desc:"The maximum permitted speed is 50 kilometres per hour.",action:"Reduce speed to 50 km/h or below before passing the sign."}},
 {id:"no-parking",cat:"prohibition",shape:"circle-blue-red",symbol:"slash",km:{name:"ហាមចត",desc:"មិនអនុញ្ញាតឱ្យចតយានយន្ត ប៉ុន្តែអាចឈប់ខ្លីដើម្បីឡើងចុះបានបើមានសុវត្ថិភាព។",action:"រកទីតាំងចតដែលមានការអនុញ្ញាត។"},en:{name:"No parking",desc:"Parking is prohibited; a very brief safe stop may be allowed where applicable.",action:"Find a designated or legally permitted parking area."}},
 {id:"no-stopping",cat:"prohibition",shape:"circle-blue-red",symbol:"cross",km:{name:"ហាមឈប់ និងហាមចត",desc:"ហាមទាំងការឈប់ និងការចតយានយន្តនៅតំបន់នេះ។",action:"បន្តដំណើរ និងកុំឈប់ លើកលែងមានអាសន្ន។"},en:{name:"No stopping",desc:"Both stopping and parking are prohibited in this area.",action:"Keep moving unless an emergency makes stopping unavoidable."}},
 {id:"weight-limit",cat:"prohibition",shape:"circle-red",symbol:"10t",km:{name:"កំណត់ទម្ងន់ ១០ តោន",desc:"ហាមយានយន្តដែលមានទម្ងន់សរុបលើស ១០ តោនឆ្លងកាត់។",action:"ពិនិត្យទម្ងន់យានយន្ត និងប្រើផ្លូវជំនួសប្រសិនបើលើសកំណត់។"},en:{name:"10-tonne limit",desc:"Vehicles with a total weight above 10 tonnes may not pass.",action:"Check gross vehicle weight and use another route if above the limit."}},
 {id:"height-limit",cat:"prohibition",shape:"circle-red",symbol:"35m",km:{name:"កំណត់កម្ពស់ ៣.៥ ម៉ែត្រ",desc:"ហាមយានយន្តដែលមានកម្ពស់លើស ៣.៥ ម៉ែត្រឆ្លងកាត់។",action:"វាស់កម្ពស់សរុប និងប្រើផ្លូវជំនួសប្រសិនបើខ្ពស់ជាងកំណត់។"},en:{name:"3.5-metre height limit",desc:"Vehicles higher than 3.5 metres may not pass.",action:"Check total height and take another route if above the limit."}},
 {id:"straight",cat:"mandatory",shape:"circle-blue",symbol:"up",km:{name:"ត្រូវទៅត្រង់",desc:"យានយន្តត្រូវធ្វើដំណើរទៅមុខត្រង់តែប៉ុណ្ណោះ។",action:"រក្សាគន្លង និងបន្តត្រង់។ កុំបត់ឆ្វេង ឬស្តាំ។"},en:{name:"Straight ahead only",desc:"Traffic must continue straight ahead only.",action:"Stay in lane and proceed straight; do not turn left or right."}},
 {id:"turn-left",cat:"mandatory",shape:"circle-blue",symbol:"left",km:{name:"ត្រូវបត់ឆ្វេង",desc:"យានយន្តត្រូវបត់ឆ្វេងនៅចំណុចនេះ។",action:"ផ្តល់សញ្ញាបត់ ពិនិត្យអ្នកប្រើផ្លូវផ្សេង និងបត់ឆ្វេងដោយសុវត្ថិភាព។"},en:{name:"Turn left",desc:"Traffic must turn left at this point.",action:"Signal, check for other road users and turn left safely."}},
 {id:"turn-right",cat:"mandatory",shape:"circle-blue",symbol:"right",km:{name:"ត្រូវបត់ស្តាំ",desc:"យានយន្តត្រូវបត់ស្តាំនៅចំណុចនេះ។",action:"ផ្តល់សញ្ញាបត់ ពិនិត្យអ្នកប្រើផ្លូវផ្សេង និងបត់ស្តាំដោយសុវត្ថិភាព។"},en:{name:"Turn right",desc:"Traffic must turn right at this point.",action:"Signal, check for other road users and turn right safely."}},
 {id:"roundabout",cat:"mandatory",shape:"circle-blue",symbol:"round",km:{name:"រង្វង់មូល",desc:"ត្រូវធ្វើដំណើរតាមទិសព្រួញជុំវិញរង្វង់មូល។",action:"បន្ថយល្បឿន ផ្តល់អាទិភាពតាមសញ្ញា និងចេញតាមច្រកដែលចង់បាន។"},en:{name:"Roundabout",desc:"Follow the direction shown around the roundabout.",action:"Slow down, yield as signed and signal before taking your exit."}},
 {id:"keep-right",cat:"mandatory",shape:"circle-blue",symbol:"downRight",km:{name:"រក្សាខាងស្តាំ",desc:"ត្រូវបើកបរឆ្លងកាត់ឧបសគ្គពីខាងស្តាំ។",action:"បន្ថយល្បឿន និងរក្សាខាងស្តាំនៃកោះចរាចរណ៍ ឬឧបសគ្គ។"},en:{name:"Keep right",desc:"Traffic must pass the obstruction on the right.",action:"Slow down and keep to the right of the island or obstruction."}},
 {id:"left-curve",cat:"warning",shape:"triangle",symbol:"curveLeft",km:{name:"ផ្លូវកោងទៅឆ្វេង",desc:"ផ្លូវខាងមុខកោងទៅខាងឆ្វេង។",action:"បន្ថយល្បឿន រក្សាគន្លង និងកុំវ៉ាជែងនៅកន្លែងមើលមិនច្បាស់។"},en:{name:"Left curve ahead",desc:"The road curves to the left ahead.",action:"Slow down, stay in lane and avoid overtaking where visibility is limited."}},
 {id:"crossroad",cat:"warning",shape:"triangle",symbol:"plus",km:{name:"ផ្លូវប្រសព្វខាងមុខ",desc:"មានផ្លូវប្រសព្វនៅខាងមុខ ដែលអាចមានយានយន្តឆ្លងកាត់។",action:"បន្ថយល្បឿន មើលទាំងសងខាង និងត្រៀមផ្តល់អាទិភាព។"},en:{name:"Crossroads ahead",desc:"A crossroads ahead may have traffic entering from either side.",action:"Slow down, check both sides and prepare to yield."}},
 {id:"pedestrian",cat:"warning",shape:"triangle",symbol:"person",km:{name:"អ្នកថ្មើរជើងឆ្លងកាត់",desc:"មានកន្លែងអ្នកថ្មើរជើងឆ្លងផ្លូវនៅខាងមុខ។",action:"បន្ថយល្បឿន និងឈប់ផ្តល់ផ្លូវដល់អ្នកថ្មើរជើង។"},en:{name:"Pedestrian crossing",desc:"A pedestrian crossing is ahead.",action:"Slow down and stop to give pedestrians priority."}},
 {id:"children",cat:"warning",shape:"triangle",symbol:"children",km:{name:"កុមារ / សាលារៀន",desc:"តំបន់មានកុមារ ឬសាលារៀននៅខាងមុខ។",action:"បន្ថយល្បឿនខ្លាំង ប្រយ័ត្នកុមារឆ្លងផ្លូវ និងត្រៀមឈប់។"},en:{name:"Children / school",desc:"Children or a school zone are ahead.",action:"Reduce speed significantly, watch for children and be ready to stop."}},
 {id:"roadworks",cat:"warning",shape:"triangle",symbol:"worker",km:{name:"ការដ្ឋានផ្លូវ",desc:"មានការជួសជុល ឬសាងសង់ផ្លូវនៅខាងមុខ។",action:"បន្ថយល្បឿន គោរពការបញ្ជារបស់អ្នកការដ្ឋាន និងប្រុងប្រយ័ត្នឧបសគ្គ។"},en:{name:"Roadworks",desc:"Road construction or maintenance is taking place ahead.",action:"Slow down, follow site directions and watch for workers and obstacles."}},
 {id:"slippery",cat:"warning",shape:"triangle",symbol:"skid",km:{name:"ផ្លូវរអិល",desc:"ផ្ទៃផ្លូវអាចរអិល ជាពិសេសពេលភ្លៀង។",action:"បន្ថយល្បឿន បង្កើនគម្លាត និងជៀសវាងចាប់ហ្វ្រាំងឬបត់ភ្លាមៗ។"},en:{name:"Slippery road",desc:"The road surface may be slippery, especially when wet.",action:"Slow down, increase following distance and avoid sudden braking or steering."}},
 {id:"narrow-bridge",cat:"warning",shape:"triangle",symbol:"narrow",km:{name:"ស្ពានតូចចង្អៀត",desc:"ស្ពានខាងមុខមានទទឹងតូចជាងផ្លូវ។",action:"បន្ថយល្បឿន សង្កេតយានយន្តមកពីមុខ និងផ្តល់អាទិភាពតាមសញ្ញា។"},en:{name:"Narrow bridge",desc:"The bridge ahead is narrower than the road.",action:"Slow down, watch oncoming traffic and yield as indicated."}},
 {id:"signals",cat:"warning",shape:"triangle",symbol:"lights",km:{name:"ភ្លើងសញ្ញាខាងមុខ",desc:"មានភ្លើងសញ្ញាចរាចរណ៍នៅខាងមុខ។",action:"បន្ថយល្បឿន និងត្រៀមឈប់នៅពេលភ្លើងប្តូរ។"},en:{name:"Traffic signals ahead",desc:"Traffic lights control the road ahead.",action:"Reduce speed and be prepared to stop when the signal changes."}},
 {id:"parking",cat:"information",shape:"square-blue",symbol:"P",km:{name:"កន្លែងចតយានយន្ត",desc:"មានទីតាំងដែលអនុញ្ញាតឱ្យចតយានយន្ត។",action:"ចតក្នុងបន្ទាត់ និងគោរពពេលវេលា ឬលក្ខខណ្ឌបន្ថែម។"},en:{name:"Parking",desc:"A designated vehicle parking area is available.",action:"Park within marked bays and follow any time or vehicle restrictions."}},
 {id:"hospital",cat:"information",shape:"square-blue",symbol:"H",km:{name:"មន្ទីរពេទ្យ",desc:"មានមន្ទីរពេទ្យ ឬមណ្ឌលសុខភាពនៅក្បែរ។",action:"បើកបរស្ងៀមស្ងាត់ និងប្រយ័ត្នរថយន្តសង្គ្រោះចេញចូល។"},en:{name:"Hospital",desc:"A hospital or medical facility is nearby.",action:"Drive quietly and watch for emergency vehicles entering or leaving."}},
 {id:"fuel",cat:"information",shape:"square-blue",symbol:"fuel",km:{name:"ស្ថានីយប្រេងឥន្ធនៈ",desc:"មានស្ថានីយប្រេងឥន្ធនៈនៅខាងមុខ ឬក្បែរនោះ។",action:"ផ្តល់សញ្ញាមុនបត់ចូល និងប្រយ័ត្នចរាចរណ៍នៅច្រកចូល។"},en:{name:"Fuel station",desc:"A fuel station is ahead or nearby.",action:"Signal before entering and watch traffic around the access point."}},
 {id:"one-way",cat:"information",shape:"square-blue",symbol:"oneWay",km:{name:"ផ្លូវឯកទិស",desc:"ផ្លូវនេះអនុញ្ញាតឱ្យធ្វើដំណើរតែមួយទិសតាមព្រួញ។",action:"ធ្វើដំណើរតាមទិសព្រួញ និងកុំបើកបរបញ្ច្រាសទិស។"},en:{name:"One-way road",desc:"Traffic may travel only in the direction shown.",action:"Follow the arrow and never drive against the permitted direction."}}
];

const state={lang:localStorage.getItem("roadsafe-lang")||"km",filter:"all",query:"",view:localStorage.getItem("roadsafe-view")||"grid"};
const el=id=>document.getElementById(id);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
function signSVG(sign){
 const white="#fff",red="#e62924",blue="#0768c9",ink="#171719",yellow="#fff";
 let body="",symbol="";
 const arrow=(dir="up")=>{const rot={up:0,left:-90,right:90,downRight:135}[dir]||0;return `<g transform="rotate(${rot} 60 60)"><path d="M60 20 38 47h14v50h16V47h14Z" fill="${white}"/></g>`};
 if(sign.shape==="stop"){body=`<polygon points="35,5 85,5 115,35 115,85 85,115 35,115 5,85 5,35" fill="${red}" stroke="white" stroke-width="7"/>`;symbol=`<text x="60" y="68" text-anchor="middle" font-family="Arial" font-size="22" font-weight="800" fill="white">STOP</text>`}
 else if(sign.shape==="yield"){body=`<polygon points="60,112 7,15 113,15" fill="white" stroke="${red}" stroke-width="10" stroke-linejoin="round"/>`}
 else if(sign.shape==="triangle"){body=`<polygon points="60,6 114,108 6,108" fill="white" stroke="${red}" stroke-width="8" stroke-linejoin="round"/>`;symbol=warningSymbol(sign.symbol,ink)}
 else if(sign.shape==="circle-blue"){body=`<circle cx="60" cy="60" r="52" fill="${blue}" stroke="white" stroke-width="5"/>`;symbol=sign.symbol==="round"?`<path d="M37 47a29 29 0 0 1 42-8l-8-12 23 4-7 22-7-10a20 20 0 0 0-32 3Zm46 27a29 29 0 0 1-42 8l8 12-23-4 7-22 7 10a20 20 0 0 0 32-3Z" fill="white"/>`:arrow(sign.symbol)}
 else if(sign.shape==="square-blue"){body=`<rect x="7" y="7" width="106" height="106" rx="8" fill="${blue}" stroke="white" stroke-width="5"/>`;symbol=infoSymbol(sign.symbol,white)}
 else {const fill=sign.shape==="circle-blue-red"?blue:white;body=`<circle cx="60" cy="60" r="52" fill="${fill}" stroke="${red}" stroke-width="9"/>`;symbol=prohibitSymbol(sign.symbol,ink,white,red)}
 return `<svg viewBox="0 0 120 120" role="img" aria-label="${escapeHtml(sign[state.lang].name)}">${body}${symbol}</svg>`
}
function prohibitSymbol(s,ink,white,red){
 const slash=`<path d="M24 22 96 98" stroke="${red}" stroke-width="10"/>`;
 if(s==="bar")return `<rect x="24" y="53" width="72" height="14" rx="3" fill="white"/>`;
 if(s==="slash")return `<path d="M27 94 93 26" stroke="${red}" stroke-width="9"/>`;
 if(s==="cross")return `<path d="M28 28 92 92M92 28 28 92" stroke="${red}" stroke-width="9"/>`;
 if(s==="leftSlash"||s==="rightSlash"){const flip=s==="rightSlash"?`transform="translate(120 0) scale(-1 1)"`:"";return `<g ${flip}><path d="M83 86V61c0-15-10-23-24-23H41" fill="none" stroke="${ink}" stroke-width="9"/><path d="m49 23-20 15 20 15" fill="none" stroke="${ink}" stroke-width="9" stroke-linejoin="round"/></g>${slash}`}
 if(s==="uSlash")return `<path d="M82 87V54a22 22 0 0 0-44 0v12" fill="none" stroke="${ink}" stroke-width="9"/><path d="m25 58 13 16 13-16" fill="none" stroke="${ink}" stroke-width="8"/>${slash}`;
 if(s==="cars")return `<rect x="24" y="47" width="31" height="26" rx="5" fill="${red}"/><circle cx="31" cy="76" r="6" fill="${ink}"/><circle cx="49" cy="76" r="6" fill="${ink}"/><rect x="64" y="40" width="31" height="32" rx="5" fill="${ink}"/><circle cx="71" cy="76" r="6" fill="${ink}"/><circle cx="89" cy="76" r="6" fill="${ink}"/>`;
 if(s==="40"||s==="50")return `<text x="60" y="75" text-anchor="middle" font-family="Arial" font-size="47" font-weight="700" fill="${ink}">${s}</text>`;
 if(s==="10t")return `<text x="60" y="69" text-anchor="middle" font-family="Arial" font-size="31" font-weight="700" fill="${ink}">10t</text>`;
 if(s==="35m")return `<path d="M33 36h54M33 84h54M38 30l-9 6 9 6M82 78l9 6-9 6" fill="none" stroke="${ink}" stroke-width="5"/><text x="60" y="68" text-anchor="middle" font-family="Arial" font-size="24" font-weight="700" fill="${ink}">3.5m</text>`;
 return "";
}
function warningSymbol(s,ink){
 if(s==="curveLeft")return `<path d="M74 88c0-22-30-18-30-43 0-8 4-14 10-18" fill="none" stroke="${ink}" stroke-width="9"/>`;
 if(s==="plus")return `<path d="M60 30v60M34 58h52" stroke="${ink}" stroke-width="9"/>`;
 if(s==="person")return `<circle cx="62" cy="37" r="7" fill="${ink}"/><path d="m60 47-8 19m8-19 12 14m-17-3 17-7M53 66 42 86m13-20 13 21" fill="none" stroke="${ink}" stroke-width="6" stroke-linecap="round"/>`;
 if(s==="children")return `<circle cx="50" cy="38" r="6" fill="${ink}"/><circle cx="70" cy="45" r="5" fill="${ink}"/><path d="m50 47-9 17m9-17 12 13M44 60 35 82m11-19 11 22m13-32-7 13m7-13 9 10m-14 1-7 20m9-19 9 18" fill="none" stroke="${ink}" stroke-width="5" stroke-linecap="round"/>`;
 if(s==="worker")return `<circle cx="63" cy="37" r="6" fill="${ink}"/><path d="m62 44-9 22m9-22 13 12M55 58 41 80m15-17 16 22M28 87h58L63 67H46Z" fill="${ink}"/>`;
 if(s==="skid")return `<path d="M38 48h42l8 24H31Zm1 24h44M42 79c-9 6-4 9-14 12m54-12c9 6 4 9 14 12" fill="none" stroke="${ink}" stroke-width="6" stroke-linecap="round"/>`;
 if(s==="narrow")return `<path d="m36 33 11 53m37-53L73 86" stroke="${ink}" stroke-width="9"/>`;
 if(s==="lights")return `<rect x="47" y="28" width="26" height="62" rx="8" fill="${ink}"/><circle cx="60" cy="42" r="7" fill="#ff3b30"/><circle cx="60" cy="59" r="7" fill="#ffcc00"/><circle cx="60" cy="76" r="7" fill="#34c759"/>`;
 return "";
}
function infoSymbol(s,white){
 if(s==="P"||s==="H")return `<text x="60" y="79" text-anchor="middle" font-family="Arial" font-size="59" font-weight="700" fill="${white}">${s}</text>`;
 if(s==="fuel")return `<path d="M35 30h34v61H35Zm7 7h20v17H42Zm27 9 10 9v27c0 8 10 8 10 0V49l-8-8" fill="none" stroke="${white}" stroke-width="6" stroke-linejoin="round"/>`;
 if(s==="oneWay")return `<path d="M20 60h63L71 43l10-6 24 23-24 23-10-6 12-17H20Z" fill="${white}"/>`;
 return "";
}

function signImage(sign){
 const name=escapeHtml(sign[state.lang].name);
 return `<span class="official-sign"><img src="${signImages[sign.id]}" alt="${name}" loading="lazy" decoding="async" referrerpolicy="no-referrer" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="svg-fallback" hidden>${signSVG(sign)}</span></span>`;
}
function fineFor(sign){if(sign.fine==="speed")return {moto:"60,000–120,000",light:"120,000–300,000",heavy:"225,000–625,000",speed:true};if(sign.cat==="warning"||sign.cat==="information")return null;return {moto:"100,000",light:"150,000",heavy:"300,000"}}
function render(){
 const t=translations[state.lang],q=state.query.trim().toLocaleLowerCase();
 const list=signs.filter(s=>(state.filter==="all"||s.cat===state.filter)&&(!q||`${s.km.name} ${s.km.desc} ${s.en.name} ${s.en.desc}`.toLocaleLowerCase().includes(q)));
 el("signGrid").className=`sign-grid ${state.view==="list"?"list":""}`;
 el("signGrid").innerHTML=list.map(s=>`<button class="sign-card" data-id="${s.id}" type="button"><div class="sign-art">${signImage(s)}</div><div class="card-topline"><div><span class="category-pill">${t.category[s.cat]}</span><h3>${s[state.lang].name}</h3><p>${s[state.lang].desc}</p></div></div><span class="card-arrow">↗</span></button>`).join("");
 el("resultsCount").textContent=t.results(list.length);el("emptyState").hidden=!!list.length;
 document.querySelectorAll(".sign-card").forEach(card=>card.addEventListener("click",()=>openModal(card.dataset.id)));
}
function setLanguage(lang){state.lang=lang;localStorage.setItem("roadsafe-lang",lang);document.documentElement.lang=lang;const t=translations[lang];document.querySelectorAll("[data-i18n]").forEach(node=>{const value=t[node.dataset.i18n];if(value!==undefined)node.innerHTML=value});el("searchInput").placeholder=t.search;document.querySelectorAll("#langToggle span").forEach((x,i)=>x.classList.toggle("active",(lang==="km"&&i===0)||(lang==="en"&&i===1)));render()}
function openModal(id){const s=signs.find(x=>x.id===id),t=translations[state.lang],d=s[state.lang],f=fineFor(s);let fineHtml=f?`<div class="fine-row"><span>${t.penalty}</span><strong>${f.moto} <small>៛</small></strong><strong>${f.light} <small>៛</small></strong><strong>${f.heavy} <small>៛</small></strong></div><div class="fine-row"><span></span><span>${t.moto}</span><span>${t.lightVehicle}</span><span>${t.heavyVehicle}</span></div>${f.speed?`<p class="modal-warning">${state.lang==="km"?"ចំនួនប្រែប្រួលតាមល្បឿនដែលលើសពីកំណត់។ កម្រិតខាងលើបង្ហាញជួរពិន័យសរុបសម្រាប់ល្មើសល្បឿន។":"Amounts vary by how far the limit is exceeded. The figures show the overall speeding-fine range."}</p>`:""}`:`<div class="fine-row"><span>${t.penalty}</span><strong style="grid-column:2/-1">${t.notFixed}</strong></div><p class="modal-warning">${t.depends}</p>`;el("modalContent").innerHTML=`<div class="modal-inner"><div class="modal-hero"><div class="modal-art">${signImage(s)}</div><div><span class="modal-category">${t.category[s.cat]}</span><h2>${d.name}</h2><p>${d.desc}</p></div></div><div class="modal-grid"><div class="modal-panel"><h3>${t.meaning}</h3><p>${d.desc}</p></div><div class="modal-panel"><h3>${t.action}</h3><p>${d.action}</p></div></div><div class="modal-fines"><div class="modal-fines-head"><h3>${t.penalty}</h3><span class="law-tag">SUB-DECREE 39</span></div>${fineHtml}<p class="modal-warning">${t.legalNote}</p></div></div>`;el("signModal").showModal()}

el("langToggle").addEventListener("click",()=>setLanguage(state.lang==="km"?"en":"km"));
el("themeToggle").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("roadsafe-theme",document.body.classList.contains("dark")?"dark":"light")});
if(localStorage.getItem("roadsafe-theme")==="dark"||(!localStorage.getItem("roadsafe-theme")&&matchMedia("(prefers-color-scheme: dark)").matches))document.body.classList.add("dark");
el("searchInput").addEventListener("input",e=>{state.query=e.target.value;render()});
el("filterRow").addEventListener("click",e=>{const btn=e.target.closest("button");if(!btn)return;state.filter=btn.dataset.filter;document.querySelectorAll(".filter-chip").forEach(x=>x.classList.toggle("active",x===btn));render()});
document.querySelectorAll("[data-view]").forEach(btn=>btn.addEventListener("click",()=>{state.view=btn.dataset.view;localStorage.setItem("roadsafe-view",state.view);document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x===btn));render()}));
document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===state.view));
el("randomSign").addEventListener("click",()=>openModal(signs[Math.floor(Math.random()*signs.length)].id));
el("modalClose").addEventListener("click",()=>el("signModal").close());el("signModal").addEventListener("click",e=>{if(e.target===el("signModal"))el("signModal").close()});
document.addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();el("searchInput").focus();el("signs").scrollIntoView()}});
document.querySelectorAll("[data-vehicle]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-vehicle]").forEach(x=>x.classList.toggle("active",x===btn));const data={moto:{amount:"100,000",km:"ម៉ូតូ ទោចក្រយានយន្តសណ្តោងរ៉ឺម៉ក ត្រីចក្រយានយន្ត និងម៉ូតូកង់៤",en:"Motorcycles, motorcycle trailers, tuk-tuks and quadricycles"},light:{amount:"150,000",km:"រថយន្តដឹកអ្នកដំណើរ ឬទំនិញធុនស្រាល តាមប្រភេទដែលច្បាប់កំណត់",en:"Light passenger and goods vehicles as legally classified"},heavy:{amount:"300,000",km:"រថយន្តដឹកជញ្ជូន ឬរថយន្តធុនធ្ងន់ តាមប្រភេទដែលច្បាប់កំណត់",en:"Heavy transport and goods vehicles as legally classified"}}[btn.dataset.vehicle];el("fineAmount").innerHTML=`${data.amount} <small>៛</small>`;el("fineVehicleText").textContent=data[state.lang]}));
const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("visible");observer.unobserve(x.target)}}),{threshold:.12});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));
el("year").textContent=new Date().getFullYear();el("signCount").textContent=signs.length;setLanguage(state.lang);
